/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "pikridas.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

float *
mesos_1(pinakas *argp, CLIENT *clnt)
{
	static float clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, mesos,
		(xdrproc_t) xdr_pinakas, (caddr_t) argp,
		(xdrproc_t) xdr_float, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

megisto *
maximum_1(pinakas *argp, CLIENT *clnt)
{
	static megisto clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, maximum,
		(xdrproc_t) xdr_pinakas, (caddr_t) argp,
		(xdrproc_t) xdr_megisto, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

fpin *
farray_1(f_plus_pin *argp, CLIENT *clnt)
{
	static fpin clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, farray,
		(xdrproc_t) xdr_f_plus_pin, (caddr_t) argp,
		(xdrproc_t) xdr_fpin, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
