/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "pikridas.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
mesos_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		pinakas mesos_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case mesos:
		_xdr_argument = (xdrproc_t) xdr_pinakas;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) mesos_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
maximum_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		pinakas maximum_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case maximum:
		_xdr_argument = (xdrproc_t) xdr_pinakas;
		_xdr_result = (xdrproc_t) xdr_megisto;
		local = (char *(*)(char *, struct svc_req *)) maximum_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
farray_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		f_plus_pin farray_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case farray:
		_xdr_argument = (xdrproc_t) xdr_f_plus_pin;
		_xdr_result = (xdrproc_t) xdr_fpin;
		local = (char *(*)(char *, struct svc_req *)) farray_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (MESOS_PROG, MESOS_VERS);
	pmap_unset (MAXIMUM_PROG, MAXIMUM_VERS);
	pmap_unset (FARRAY_PROG, FARRAY_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, MESOS_PROG, MESOS_VERS, mesos_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MESOS_PROG, MESOS_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, MAXIMUM_PROG, MAXIMUM_VERS, maximum_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MAXIMUM_PROG, MAXIMUM_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, FARRAY_PROG, FARRAY_VERS, farray_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (FARRAY_PROG, FARRAY_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, MESOS_PROG, MESOS_VERS, mesos_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MESOS_PROG, MESOS_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, MAXIMUM_PROG, MAXIMUM_VERS, maximum_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MAXIMUM_PROG, MAXIMUM_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, FARRAY_PROG, FARRAY_VERS, farray_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (FARRAY_PROG, FARRAY_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
